
###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts/673896091f604a2783ce6387


###

GET http://localhost:3000/posts/by-sender?sender=Yonatan

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "sender": "Yonatan",
    "title": "My third post",
    "content": "This is my third post"
}

###

PUT http://localhost:3000/posts/673a2275ba0de1080f2a273b
Content-Type: application/json

{
    "sender": "Yonatan",
    "title": "My third post - update2",
    "content": "This is the third updated content"
}

###

POST http://localhost:3000/comments
Content-Type: application/json

{
    "content": "I really liked it!",
    "postId": "673a2275ba0de1080f2a273b",
    "sender": "Yonatan"
}

###

GET http://localhost:3000/comments

###

GET http://localhost:3000/comments/posts/673896091f604a2783ce6387

###

PUT http://localhost:3000/comments/673a185038de392dd531e44f
Content-Type: application/json

{
    "content": "updated comment content"
}

###

DELETE http://localhost:3000/comments/673a187138de392dd531e451

###